### ISSUE TITLE
No podspec found 

### ISSUE THREAD

**Issue by arelstone** [VGamezz19/react-native-sketch-draw#14]
When installing this package and running `pod install` I get this error
`[!] No podspec found for 'P41Sketch' in '../node_modules/react-native-sketch-draw'` when though i see the podspec file in the repo

### Environment
System:
    OS: macOS 10.15.1
    CPU: (12) x64 Intel(R) Core(TM) i7-8750H CPU @ 2.20GHz
    Memory: 3.32 GB / 16.00 GB
    Shell: 5.7.1 - /bin/zsh

  Binaries:
    Node: 12.11.1 - /usr/local/bin/node
    Yarn: 1.17.3 - /usr/local/bin/yarn
    npm: 6.11.3 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman

  SDKs:
    iOS SDK:
      Platforms: iOS 12.1, macOS 10.14, tvOS 12.1, watchOS 5.1
    Android SDK:
      API Levels: 23, 25, 26, 28
      Build Tools: 23.0.1, 28.0.3
      System Images: android-28 | Google Play Intel x86 Atom

  IDEs:
    Android Studio: 3.4 AI-183.6156.11.34.5522156
    Xcode: 10.1/10B61 - /usr/bin/xcodebuild

  npmGlobalPackages:
    react-native-cli: 2.0.1
    react-native: 0.59.5

### Steps to Reproduce

1. `npm install react-native-sketch-draw --save`
2. `react-native link react-native-sketch-draw`
3. `cd ios && pod install`

**Comment by SimonErm** [comment]
fixed on master. @VGamezz19 can you do another release?
