### ISSUE TITLE
The `P41Sketch` pod failed to validate due to Missing required attribute `homepage`

### ISSUE THREAD

**Issue by keremaydin52** [VGamezz19/react-native-sketch-draw#15]
Hello,

After installing the package, I'm getting this error.

[!] The `P41Sketch` pod failed to validate due to 1 error:
    - ERROR | attributes: Missing required attribute `homepage`.
    - WARN  | source: The version should be included in the Git tag.
    - WARN  | description: The description is equal to the summary.

I'm not sure but as I understand I need to add a homepage attribute in a podspec file and I don't know how to do this. Please help me.

### Environment

System:
    OS: macOS 10.15.3
    CPU: (4) x64 Intel(R) Core(TM) i5-5257U CPU @ 2.70GHz
    Memory: 141.16 MB / 8.00 GB
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 12.10.0 - /usr/local/bin/node
    Yarn: 1.19.0 - /usr/local/bin/yarn
    npm: 6.14.1 - /usr/local/bin/npm
    Watchman: 4.9.0 - /usr/local/bin/watchman
  SDKs:
    iOS SDK:
      Platforms: iOS 13.2, DriverKit 19.0, macOS 10.15, tvOS 13.2, watchOS 6.1
  IDEs:
    Xcode: 11.3.1/11C504 - /usr/bin/xcodebuild
  npmPackages:
    react: 16.9.0 => 16.9.0 
    react-native: 0.61.5 => 0.61.5 
  npmGlobalPackages:
    react-native-cli: 2.0.1

### Steps to Reproduce

1. `npm install react-native-sketch-draw`
2. `cd ios && pod install && cd ..`

**Comment by prayaslashkari** [comment]
@keremaydin52 I'm still facing this problem. What to do?

**Comment by keremaydin52** [comment]
> @keremaydin52 I'm still facing this problem. What to do?

I'm not using this package anymore but as far as I remember you need to find Pods -> Local Podspecs -> P41Sketch.podspec.json file. Then add this line;
`"homepage": "https://github.com/VGamezz19/react-native-sketch-draw#readme"`
to the json file.

**Comment by prayaslashkari** [comment]
@keremaydin52 which package did you use in place of this? just curious and need reviews. Thanks!

**Comment by prayaslashkari** [comment]
By the way this made it work.

Add this line.
"homepage": "https://github.com/VGamezz19/react-native-sketch-draw#readme"

<img width="789" alt="image" src="https://user-images.githubusercontent.com/25193916/103031468-e3cfa280-4583-11eb-8dcb-f61c4ee3fd76.png">

**Comment by keremaydin52** [comment]
I have used that one later.
https://github.com/terrylinla/react-native-sketch-canvas#readme
