### ISSUE TITLE
The prop toolColor is not working in iOS. Does work in Android.

### ISSUE THREAD

**Issue by diego-caceres** [VGamezz19/react-native-sketch-draw#3]
Using the yellow color '#FFFA38' from the Readme, in Android I get the expected result, but in iOS this prop seems to be ignored, I always get a black line.

**Comment by VGamezz19** [comment]
Hey @diego-caceres  I see that you use the version `@=> 0.48.1`, for this package, it is mandatory to use v5.3 to avoid problems like that...
Please take It easy, and reinstall all your dependencies creating a new project with correct version

Please, share if this works to you, tnx

**Comment by diego-caceres** [comment]
Hi @VGamezz19 , thanks for the reply. 

I'm not sure why react-native info command threw 0.48 for react native the other day, but in reality I'm using 0.55.2 and I still have this error. 
I've also tried react-native 0.53 just in case, but the drawing line is always black in iOS. 

Should it be exactly 0.53 or it should work on newer? 

Thanks

**Comment by diego-caceres** [comment]
Ok, so I created a new project from scratch, with version 0.53 (instead of downgrading my existing one) and now the line color props is working correctly!

**Comment by VGamezz19** [comment]
Nice @diego-caceres  try it the same from issue #2 ,)
